### ISSUE TITLE
ocr quality function

### ISSUE THREAD

**Issue by soodoku** [sckott/extractr#13]
Dear Scott,

It may be a good idea to provide a way to quantify the quality of OCR. To that end, see:
https://github.com/soodoku/recognize

I plan to expand that package. But in the interim, I have added the basic function in abbyyR at: 
https://github.com/soodoku/abbyyR/blob/master/R/compareText.R

**Comment by sckott** [comment]
@soodoku cool, looks interesting, i'll check it out
