### ISSUE TITLE
Rcampdf

### ISSUE THREAD

**Issue by soodoku** [sckott/extractr#17]
When I try `load_all("R")` in devtools, trying to get the package going, I get:

```
Loading extractr
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package Rcampdf not available.
```
Tried looking this up but can't find it.

**Comment by sckott** [comment]
did you figure it out?  pretty sure i removed it from this pkg

**Comment by soodoku** [comment]
I did. I was using my local copy. Apologies. Working on submitting a few simple things.

**Comment by sckott** [comment]
cool!
