### ISSUE TITLE
Import abbyyR

### ISSUE THREAD

**Issue by sckott** [sckott/extractr#4]
https://github.com/soodoku/abbyyR 

@soodoku

as a web API option, does OCR too

**Comment by sckott** [comment]
@soodoku let me know when I should try to incorporate here

**Comment by soodoku** [comment]
Dear Scott, 

I think you can incorporate it. Everything works as expected, afaik. 

The number of API endpoints that Abbyy offers is a bit much -- it offers speciality functions for barcodes, machine readable documents, business cards etc. 

For now everything is its own function. And specific arguments differ a bit so not sure how much rationalization we can do. At any rate, please take a look. And open up issues etc. if you see that things can be implemented in a better way.

**Comment by sckott** [comment]
Okay, will do, thanks for the message.
