### ISSUE TITLE
Use tesseract

### ISSUE THREAD

**Issue by sckott** [sckott/extractr#5]
https://github.com/tesseract-ocr
- is there a web API option?
- local via the C++ API https://github.com/tesseract-ocr/tesseract/wiki/APIExample

**Comment by soodoku** [comment]
Dear S,

This also uses tesseract:
https://github.com/soodoku/image-to-text

Tesseract supports a whole host of options including generating own training data etc. Ideally we would want to implement a way to pass some of those options esp. given R has wonderful tools for training a model.

Warmly,
Gaurav

**Comment by sckott** [comment]
right, I think we can get some help on wrapping the C++ API for tesseract, and make it a nice experience

**Comment by sckott** [comment]
looks like duncan has a wrapper here https://github.com/duncantl/Rtesseract

**Comment by soodoku** [comment]
Nice! As Duncan mentions, a somewhat basic implementation for the time being. But very likely a good short term solution to get extract going. By the way, I was thinking of proposing that you rename the package: extractr. Just thought it sounded more fun.

**Comment by sckott** [comment]
@soodoku `extractr` sounds good to me
