### ISSUE TITLE
Link to Captricity

### ISSUE THREAD

**Issue by soodoku** [sckott/extractr#7]
https://shreddr.captricity.com/developer/overview/

**Comment by sckott** [comment]
@soodoku  thanks - 
- they have a non-profit program, see if ropensci can use it http://captricity.org/

**Comment by soodoku** [comment]
Dear Scott,

At long last, finished first version of package that links up to Captricity. 

https://github.com/soodoku/captr

**Comment by sckott** [comment]
Nice. looks good. 

question about licenses: Any reason for using GPL?  I am no expert on licenses, but from what I understand, companies often can't use GPL licensed software - The only concern I have is if this pkg (which is MIT) depends on something that is GPL, if that makes people less likely to use this pkg. however, `tm` is GPL as well, which we already depend on, so I guess it's a moot point. Anyway, just curious.

**Comment by soodoku** [comment]
Righto. I don't know either. Saw responses to your tweet. Will change to MIT.

**Comment by sckott** [comment]
okay, thanks!
